export enum PermissionsEnum {
  CREATE_TASK = 'CREATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MANAGE_COURSE = 'MANAGE_COURSE',
  SEND_ANNOUNCEMENT = 'SEND_ANNOUNCEMENT',
  GRADE_SUBMISSION = 'GRADE_SUBMISSION',
  JOIN_COURSE = 'JOIN_COURSE',
  INVITE_MEMBERS = 'INVITE_MEMBERS',
  MANAGE_MEMBERS = 'MANAGE_MEMBERS',
  CREATE_CHANNELS = 'CREATE_CHANNELS',
  DELETE_MESSAGES = 'DELETE_MESSAGES',
}

export const ALL_PERMISSIONS = Object.values(PermissionsEnum);
